#!/bin/bash

NzList=(20 20 20 20 40 40 40 40 80 80 80 80)
NxList=(400 400 400 400 800 800 800 800 1600 1600 1600 1600)
dtList=(0.005 0.01 0.02 0.04 0.0025 0.005 0.01 0.02 0.00125 0.0025 0.005 0.01)
CoList=(01 02 04 08 01 02 04 08 01 02 04 08)

export L=20
export T=19
export ny=1
export y1=-.1
export y2=.1
export Ux=1
export Uy=0
export Uz=0

for n in ${!NzList[*]} 
do
    export nx=${NxList[$n]}
    export nz=${NzList[$n]}
    export dt=${dtList[$n]}
    caseName=N${NzList[$n]}Co${CoList[$n]}
    echo $caseName
    cp -r baseCase $caseName
    envsubst < baseCase/constant/polyMesh/blockMeshDict > ${caseName}/constant/polyMesh/blockMeshDict
    envsubst < baseCase/system/controlDict > ${caseName}/system/controlDict
    envsubst < baseCase/0.org/U > ${caseName}/0.org/U
    touch ${caseName}/${caseName}.foam
done
