#!/bin/bash

NzList=(20 20 20 20 40 40 40 40 80 80 80 80)
NxList=(400 400 400 400 800 800 800 800 1600 1600 1600 1600)
dtList=(0.005 0.01 0.02 0.04 0.0025 0.005 0.01 0.02 0.00125 0.0025 0.005 0.01)
CoList=(01 02 04 08 01 02 04 08 01 02 04 08)

for n in ${!NzList[*]} 
do 
    export nx=${NxList[$n]}
    export nz=${NzList[$n]}
    export dt=${dtList[$n]}
    caseName=N${NzList[$n]}Co${CoList[$n]}_test
    echo $caseName
    echo $nx
    cp -r baseCase $caseName
    envsubst < baseCase/constant/polyMesh/blockMeshDict > ${caseName}/constant/polyMesh/blockMeshDict
    envsubst < baseCase/system/controlDict > ${caseName}/system/controlDict
#    cp -r baseCase $caseName
#    cd $caseName
#    ./Allrun &
#    cd ..
done
