#!/bin/bash
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

rm -rf 0
cp -r 0.orig 0
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication setAlphaField
runApplication $(getApplication)

#------------------------------------------------------------------------------
