#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

#Find out which OF version is loaded
if [ -z "$WM_PROJECT_VERSION" ];
then
    echo " "
    echo "No OpenFOAM version seems to be sourced."
    echo "Please source one of the supported OpenFOAM versions."
    echo "Aborting isoAdvector cleaning."
    echo " "
elif [ "$WM_PROJECT" == "foam" ];
then
    sourceDir=foam-extend-$WM_PROJECT_VERSION
elif [ "$WM_PROJECT" == "OpenFOAM" ];
then
    sourceDir=OpenFOAM-$(echo $WM_PROJECT_VERSION | sed s/\.x$/\.0/)
fi

#Compile the correct isoAdvector version
if [ -n "$sourceDir" ];
then
    export ISOADVECTION=$PWD/src/$sourceDir
    src/$sourceDir/Allwclean
    applications/$sourceDir/Allwclean
fi
