#!/bin/bash
cd ${0%/*} || exit 1   # run from this directory

#Compile in debug mode?
if [ "$1" == "debug" ];
then
    export ISODEBUG="-g -DFULL_DEBUG"
fi

#Write A LOT OF debug information to log file.
#The info is poorly explained so you probably don't want this.
if [ "$1" == "log" ];
then
    export DETAILSTOLOGSWITCH=DETAILS2LOG
else
    export DETAILSTOLOGSWITCH=OFF
fi

#. etc/bashrc

#Find out which OF version is loaded
if [ -z "$WM_PROJECT_VERSION" ];
then
    echo " "
    echo "No OpenFOAM version seems to be sourced."
    echo "Please source one of the supported OpenFOAM versions."
    echo "Aborting isoAdvector installation."
    echo " "
elif [ "$WM_PROJECT" == "foam" ];
then
    sourceDir=foam-extend-$WM_PROJECT_VERSION
elif [ "$WM_PROJECT" == "OpenFOAM" ];
then
    sourceDir=OpenFOAM-$(echo $WM_PROJECT_VERSION | sed s/\.x$/\.0/)
fi

#Compile the correct isoAdvector version
if [ -n "$sourceDir" ];
then
    export ISOADVECTION=$PWD/src/$sourceDir
    src/$sourceDir/Allwmake
    applications/$sourceDir/Allwmake
fi

unset ISODEBUG
unset DETAILSTOLOGSWITCH
export ISOADVECTOR_ROOT_DIR=$PWD
