#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

if [ "$1" == "debug" ];
then
    export ISODEBUG="-g -DFULL_DEBUG"
fi

if [ "$1" == "log" ];
then
    export DETAILSTOLOGSWITCH=DETAILSTOLOG
else
    export DETAILSTOLOGSWITCH=OFF
fi

. etc/bashrc

src/Allwmake
applications/Allwmake

unset ISODEBUG 
unset DETAILSTOLOGSWITCH
