#!/bin/bash
cd ${0%/*} || exit 1   # run from this directory

echo "Installing isoAdvector..."

#Find out which OF version is loaded
if [ -z "$WM_PROJECT_VERSION" ];
then
    echo " "
    echo "No OpenFOAM/foam-extend version seems to be sourced."
    echo "Please source one of the supported OpenFOAM versions."
    echo "Aborting isoAdvector installation."
    echo " "
elif [ "$WM_PROJECT" == "foam" ];
then
    sourceDir=foam-extend-$WM_PROJECT_VERSION
elif [ "$WM_PROJECT" == "OpenFOAM" ];
then
    sourceDir=OpenFOAM-${WM_PROJECT_VERSION}

    echo "Copying non-existing files from src/OpenFOAM to src/$sourceDir and"
    echo "from applications/OpenFOAM to applications/${sourceDir}..."

    mkdir -p src/$sourceDir
    cp -nr src/OpenFOAM/* src/$sourceDir/

    mkdir -p applications/$sourceDir
    cp -nr applications/OpenFOAM/* applications/$sourceDir/

    #Only convert src if not one of the newest OF versions
    if [[ "$WM_PROJECT_VERSION" != "4."* ]] && \
       [ "$WM_PROJECT_VERSION" != "v1612+" ] && \
       [ "$WM_PROJECT_VERSION" != "plus" ];
    then
       #Transform code to old API
       cd bin
       ./generateCodeForOldVersion $WM_PROJECT_VERSION
       cd -
    fi
    
    #Generate interFlow solver from interFoam solver of the loaded OF version
    cd bin
    ./generateInterFlow
    cd -
fi

#Compile the correct isoAdvector version
if [ -n "$sourceDir" ];
then
    ISOADVECTION=$PWD/src/$sourceDir
    if [ -d "$ISOADVECTION" ]; then
        export ISOADVECTION
        echo "Compiling src/${sourceDir}..."
        src/${sourceDir}/Allwmake
        echo "Compiling applications/${sourceDir}..."
        applications/${sourceDir}/Allwmake
    else
       echo
       echo "The directory $ISOADVECTION does not exist"
       echo "If you are compiling isoAdvector with and older OF"
       echo "you might need to run bin/generateCodeForOldVersion"
       echo "before compiling."
       echo
    fi
fi
