#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

#Find out which OF version is loaded
if [ -z "$WM_PROJECT_VERSION" ];
then
    echo " "
    echo "No OpenFOAM version is sourced."
    echo "Please source one of the supported OpenFOAM versions."
    echo "Aborting isoAdvector cleaning."
    echo " "
elif [ "$WM_PROJECT" == "foam" ];
then
    sourceDir=foam-extend-$WM_PROJECT_VERSION
elif [ "$WM_PROJECT" == "OpenFOAM" ];
then
    sourceDir=OpenFOAM-${WM_PROJECT_VERSION}
fi

#Compile the correct isoAdvector version
if [ -n "$sourceDir" ];
then
    ISOADVECTION=$PWD/src/$sourceDir
    if [ -d "$ISOADVECTION" ]; then
        export ISOADVECTION
        src/${sourceDir}/Allwclean
        applications/$sourceDir/Allwclean
    else
       echo
       echo "The directory $ISOADVECTION does not exist."
       echo "Aborting cleaning."
       echo
    fi
fi
