#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -x 

wmake solvers/interFlower
wmake solvers/isoAdvector
wmake solvers/mulesFoam
wmake solvers/passiveAdvectionFoam

wmake all test
wmake all utilities/preProcessing
wmake all utilities/postProcessing
