#!/bin/bash

NxList=(100)
NyList=(40)
NzList=(20)
dtList=(0.025)
CoList=(05)

export L=5
export H=1
export y1=0
export y2=2
export T=4
export Ux=1
export Uy=0.2
export Uz=0.1
export solver=isoAdvect #Change to interFoam to run with MULES

for n in ${!NzList[*]} 
do
    export nx=${NxList[$n]}
    export ny=${NyList[$n]}
    export nz=${NzList[$n]}
    export dt=${dtList[$n]}
    caseName=N${NzList[$n]}Co${CoList[$n]}
    echo $caseName
    cp -r baseCase $caseName
    envsubst < baseCase/constant/polyMesh/blockMeshDict > ${caseName}/constant/polyMesh/blockMeshDict
    envsubst < baseCase/system/controlDict > ${caseName}/system/controlDict
    envsubst < baseCase/0.org/U > ${caseName}/0.org/U
    touch ${caseName}/${caseName}.foam
done
