#!/bin/bash

#schemeList=(isoAdvector MULES HRIC CICSAM)
schemeList=(isoAdvector)
meshList=(hex tri poly)
#meshList=(hex)
CoList=(0.5)

#Location of tri meshes
triMeshDir=triMeshes

errorFile=errors.log
rm $errorFile

for nn in ${!meshList[*]}
do
	meshType=${meshList[$nn]}

	for mm in ${!schemeList[*]}
	do
		scheme=${schemeList[$mm]}
		echo $meshType >> $errorFile
		echo $scheme >> $errorFile

		#Case location
		series=$PWD/$scheme/$meshType

		printHeader=yes
		for n in $(ls "$series");
		do
			caseDir=$series/$n
			echo $caseDir
			echo $n >> $errorFile
			uniFlowErrors -case $caseDir -latestTime > tmpfile
			if [ "$printHeader" = "yes" ];
			then
				tail -2 tmpfile >> $errorFile
				printHeader=no
			else
				tail -1 tmpfile >> $errorFile
			fi
		done
	done
done
rm tmpfile
