#!/bin/sh

application=$(sed -E -n "s%^application[[:space:]]+([^[:space:]]+);%\1%p" system/controlDict)


mkdir logs

if [ -n "$application" ]
then
    $application > logs/${application}.log 2>&1

    foamToVTK -surfaceFields
fi
