#!/bin/sh

nProc=$(sed -ne "s/^numberOfSubdomains *\(.*\);/\1/p" system/decomposeParDict)
application=$(sed -ne "s/^application *\(.*\);/\1/p" system/controlDict)
jobStart=$(date +"%Y%m%d%H%M")

if [ ! -d "logs" ]; then
	cp -r 0.org 0
	mkdir logs
	blockMesh > logs/blockMesh.log 2>&1
        topoSet -dict constant/polyMesh/topoSetDict1 > logs/topoSetDict1.log 2>&1
        refineMesh -dict constant/polyMesh/refineMeshDict1 -overwrite > logs/refineMeshDict1.log 2>&1

        topoSet -dict constant/polyMesh/topoSetDict2 > logs/topoSetDict2.log 2>&1
        refineMesh -dict constant/polyMesh/refineMeshDict2 -overwrite > logs/refineMeshDict2.log 2>&1

        isoSurf > logs/isoSurf.log 2>&1
else
	mv logs logs_$jobStart
	mkdir logs
fi

if [ "$nProc" -gt "1" ]; 
then
	if [ ! -d "processor0" ]; then
                decomposePar > logs/decomposePar.log 2>&1
	fi
	mpirun -np $nProc $application -parallel > logs/$application.log 2>&1
else
	$application > logs/$application.log 2>&1
fi
