#!/bin/sh

application=$(sed -ne "s/^application\s*\(.*\);/\1/p" system/controlDict)
jobStart=$(date +"%Y_%m_%d_%H_%M")

if [ ! -d "logs" ];
then
        mkdir logs
else
        mv logs logs_$jobStart
        mkdir logs
fi

if [ ! -d "0" ]; then
        cp -r 0.org 0
fi

if [ ! -f "constant/polyMesh/points" ];
then
        blockMesh > logs/blockMesh.log 2>&1
fi

isoSurf > logs/isoSurf.log 2>&1

$application > logs/${application}.log 2>&1
