#!/bin/bash
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

rm -rf 0 isoFaces logs
cleanCase

#------------------------------------------------------------------------------
