#!/bin/bash

nProc=$(sed -E -n "s%^numberOfSubdomains[[:space:]]+([^[:space:]]+);%\1%p" system/decomposeParDict)
application=$(sed -E -n "s%^application[[:space:]]+([^[:space:]]+);%\1%p" system/controlDict)
jobStart=$(date +"%Y%m%d%H%M")

if [ ! -d "logs" ]; then

    cp -r 0.org 0
    mkdir logs
    blockMesh > logs/blockMesh.log 2>&1

    if [ "$WM_PROJECT" == "foam" ];
    then

        cp constant/polyMesh/cellSetDict1 system/cellSetDict
        cp constant/polyMesh/refineMeshDict1 system/refineMeshDict
        cellSet > logs/cellSetDict1.log 2>&1
        refineMesh -dict -overwrite > logs/refineMeshDict1.log 2>&1

        cp constant/polyMesh/cellSetDict2 system/cellSetDict
        cp constant/polyMesh/refineMeshDict2 system/refineMeshDict
        cellSet > logs/cellSetDict2.log 2>&1
        refineMesh -dict -overwrite > logs/refineMeshDict2.log 2>&1

        cp constant/transportProperties.old constant/transportProperties

        setAlphaField > logs/setAlphaField.log 2>&1

    elif [ "$WM_PROJECT" == "OpenFOAM" ];
    then
        topoSet -dict constant/polyMesh/topoSetDict1 > logs/topoSetDict1.log 2>&1
        refineMesh -dict constant/polyMesh/refineMeshDict1 -overwrite > logs/refineMeshDict1.log 2>&1

        topoSet -dict constant/polyMesh/topoSetDict2 > logs/topoSetDict2.log 2>&1
        refineMesh -dict constant/polyMesh/refineMeshDict2 -overwrite > logs/refineMeshDict2.log 2>&1

        setAlphaField > logs/setAlphaField.log 2>&1
    fi

else
    mv logs logs_$jobStart
    mkdir logs
fi

if [ -n "$application" ]
then
    if [ "$nProc" -gt "1" ];
    then
        if [ ! -d "processor0" ]; then
            decomposePar > logs/decomposePar.log 2>&1
        fi
        mpirun -np $nProc $application -parallel > logs/$application.log 2>&1
    else
        $application > logs/$application.log 2>&1
    fi
else
    echo
    echo "Can not get application to run. Exiting."
    echo
fi
