#!/bin/bash

application=$(sed -E -n "s%^application[[:space:]]+([^[:space:]]+);%\1%p" system/controlDict)

cp -r 0.orig 0

mkdir logs

blockMesh > logs/blockMesh.log 2>&1
setFields > logs/setFields.log 2>&1

if [ -n "$application" ]
then
    $application > logs/${application}.log 2>&1
else
    echo
    echo "Can not get application name to run. Exiting."
    echo
fi
