#!/bin/sh

application=$(sed -E -n "s%^application[[:space:]]+([^[:space:]]+);%\1%p" system/controlDict)
jobStart=$(date +"%Y_%m_%d_%H_%M")

if [ ! -d "logs" ]; then
    mkdir logs
else
    mv logs logs_$jobStart
    mkdir logs
fi

if [ ! -d "0" ]; then
    cp -r 0.org 0
fi

if [ ! -f "constant/polyMesh/points" ]; then
    blockMesh > logs/blockMesh 2>&1
fi

cd generateU
wmake
cd ..

generateU/generateU > logs/generateU.log 2>&1
setAlphaField > logs/setAlphaField.log 2>&1
setFields > logs/setFields.log 2>&1

if [ -n "$application" ]
then
    $application > logs/${application}.log 2>&1
else
    echo
    echo "Can not find application to run. Exiting."
    echo
fi
