#!/bin/bash

nProc=$(sed -E -n "s%^numberOfSubdomains[[:space:]]+([^[:space:]]+);%\1%p" system/decomposeParDict)
application=$(sed -E -n "s%^application[[:space:]]+([^[:space:]]+);%\1%p" system/controlDict)
jobStart=$(date +"%Y%m%d%H%M")

if [ ! -d "logs" ]; then

    cp -r 0.orig 0
    mkdir logs
    blockMesh > logs/blockMesh.log 2>&1

    setAlphaField > logs/setAlphaField.log 2>&1

else
    mv logs logs_$jobStart
    mkdir logs
fi

if [ -n "$application" ]
then
    if [ "$nProc" -gt "1" ];
    then
        if [ ! -d "processor0" ]; then
            decomposePar > logs/decomposePar.log 2>&1
        fi
        mpirun -np $nProc $application -parallel > logs/$application.log 2>&1
    else
        $application > logs/$application.log 2>&1
    fi
else
    echo
    echo "Can not get application to run. Exiting."
    echo
fi
