#!/bin/sh

./Allclean

nProc=$(sed -ne "s/^numberOfSubdomains *\(.*\);/\1/p" system/decomposeParDict)
application=$(sed -ne "s/^application *\(.*\);/\1/p" system/controlDict)
jobStart=$(date +"%Y%m%d%H%M")
#host=$HOSTNAME

if [ ! -d "logs" ]; then
        mkdir logs
        cp -r 0.org 0
        blockMesh > logs/blockMesh.log 2>&1
        topoSet -dict constant/polyMesh/topoSetDict > logs/topoSetDict.log 2>&1
        refineMesh -dict constant/polyMesh/refineMeshDict -overwrite > logs/refineMeshDict.log 2>&1
	iso2VOF > logs/iso2VOF.log 2>&1
else
        mv logs logs_$jobStart
        mkdir logs
fi


if [ "$nProc" -gt "1" ];
then
        if [ ! -d "processor0" ]; then
                decomposePar > logs/decomposePar.log 2>&1
        fi
        mpirun -np $nProc $application -parallel > logs/$application.log 2>&1
else
        $application > logs/$application.log 2>&1
fi

